#!/usr/bin/env node
/**
 * Count new scenarios generated by the supply chain in this run.
 * Reads the supply log and sums new scenarios from the most recent entries
 * (within the last hour). Outputs a single number to stdout.
 */

import { readFileSync, existsSync } from 'fs';
import { join, resolve } from 'path';

const pkgRoot = resolve(import.meta.dir, '..', '..');
const logPath = join(pkgRoot, 'data', 'supply-log.jsonl');

if (!existsSync(logPath)) {
  console.log('0');
  process.exit(0);
}

const oneHourAgo = new Date(Date.now() - 60 * 60 * 1000).toISOString();
let total = 0;

const lines = readFileSync(logPath, 'utf-8').split('\n').filter(l => l.trim());
for (const line of lines) {
  try {
    const entry = JSON.parse(line);
    if (entry.timestamp >= oneHourAgo) {
      total += entry.new ?? entry.generated ?? 0;
    }
  } catch { /* skip */ }
}

console.log(String(total));
