/**
 * External Scenario Loader — Deserialize Fault-Derived Scenarios
 * ===============================================================
 *
 * Converts SerializedScenario (JSON, no functions) into VerifyScenario
 * (with invariant checks). This is the bridge between the external
 * scenario registry and the self-test runner.
 *
 * Invariants are derived from the scenario's intent:
 * - false_positive: verify SHOULD fail (expectedSuccess: false)
 * - false_negative: verify SHOULD pass (expectedSuccess: true)
 * - bad_hint: narrowing should be present and useful
 * - regression_guard: verify should match expectedSuccess
 */

import { existsSync, readFileSync, readdirSync } from 'fs';
import { join } from 'path';
import type { VerifyScenario, InvariantCheck, InvariantVerdict } from './types.js';
import type { VerifyResult } from '../../src/types.js';
import { ExternalScenarioStore } from '../../src/store/external-scenarios.js';
import type { SerializedScenario } from '../../src/store/external-scenarios.js';

/**
 * Load external scenarios from a registry file and convert to VerifyScenario[].
 */
export function loadExternalScenarios(registryPath: string, appDir: string): VerifyScenario[] {
  const store = new ExternalScenarioStore(registryPath);
  const serialized = store.all();

  return serialized.map(s => deserialize(s, appDir));
}

/**
 * Load universal scenarios from fixtures/scenarios/universal.json.
 * These are health-checked, portable scenarios that always run against demo-app.
 * They test verify gate logic (CSS spec, shorthand, color normalization) that
 * applies to ANY app — not app-specific selectors or routes.
 */
export function loadUniversalScenarios(fixtureDir: string): VerifyScenario[] {
  const universalPath = join(fixtureDir, '..', 'scenarios', 'universal.json');
  if (!existsSync(universalPath)) return [];

  try {
    const raw = JSON.parse(readFileSync(universalPath, 'utf-8')) as SerializedScenario[];
    return raw.map(s => deserialize(s, fixtureDir));
  } catch {
    return [];
  }
}

/**
 * Load all per-gate staged scenario files from fixtures/scenarios/*-staged.json.
 * These are SerializedScenario format (same as universal.json).
 * Excludes wpt-staged.json (loaded separately via loadWPTScenarios).
 */
export function loadStagedScenarios(fixtureDir: string): VerifyScenario[] {
  const scenariosDir = join(fixtureDir, '..', 'scenarios');
  if (!existsSync(scenariosDir)) return [];

  try {
    const files = readdirSync(scenariosDir)
      .filter(f => f.endsWith('-staged.json') && f !== 'wpt-staged.json');
    const all: VerifyScenario[] = [];
    for (const file of files) {
      try {
        const raw = JSON.parse(readFileSync(join(scenariosDir, file), 'utf-8')) as SerializedScenario[];
        // Filter out non-conforming scenarios (e.g., message-staged uses envelope/policy format)
        const conforming = raw.filter(s => Array.isArray(s.edits) && Array.isArray(s.predicates));
        all.push(...conforming.map(s => deserialize(s, fixtureDir)));
      } catch { /* skip malformed files */ }
    }
    return all;
  } catch {
    return [];
  }
}

/**
 * Load real-world scenarios from fixtures/scenarios/real-world/*-staged.json.
 * These are generated by harvest-real.ts from external data sources.
 * Every scenario has source: 'real-world'.
 */
export function loadRealWorldScenarios(fixtureDir: string): VerifyScenario[] {
  const realWorldDir = join(fixtureDir, '..', 'scenarios', 'real-world');
  if (!existsSync(realWorldDir)) return [];

  try {
    const files = readdirSync(realWorldDir)
      .filter(f => f.endsWith('-staged.json'));
    const all: VerifyScenario[] = [];
    for (const file of files) {
      try {
        const raw = JSON.parse(readFileSync(join(realWorldDir, file), 'utf-8')) as SerializedScenario[];
        const conforming = raw.filter(s => Array.isArray(s.edits) && Array.isArray(s.predicates));
        all.push(...conforming.map(s => deserialize(s, fixtureDir)));
      } catch { /* skip malformed files */ }
    }
    return all;
  } catch {
    return [];
  }
}

/**
 * Load WPT harvested scenarios from fixtures/scenarios/wpt-staged.json.
 * Converts HarvestedLeaf format to VerifyScenario.
 */
export function loadWPTScenarios(fixtureDir: string): VerifyScenario[] {
  const wptPath = join(fixtureDir, '..', 'scenarios', 'wpt-staged.json');
  if (!existsSync(wptPath)) return [];

  try {
    const raw = JSON.parse(readFileSync(wptPath, 'utf-8')) as any[];
    return raw.map(leaf => deserializeWPTLeaf(leaf, fixtureDir)).filter(Boolean) as VerifyScenario[];
  } catch {
    return [];
  }
}

/**
 * Convert a WPT HarvestedLeaf into a VerifyScenario.
 */
function deserializeWPTLeaf(leaf: any, appDir: string): VerifyScenario | null {
  if (!leaf.id || !leaf.edit || !leaf.predicate) return null;

  const predicates: any[] = [{
    type: leaf.predicate.type,
    ...(leaf.predicate.selector && { selector: leaf.predicate.selector }),
    ...(leaf.predicate.property && { property: leaf.predicate.property }),
    ...(leaf.predicate.expected && { expected: leaf.predicate.expected }),
    ...(leaf.predicate.pattern && { pattern: leaf.predicate.pattern }),
    ...(leaf.predicate.file && { file: leaf.predicate.file }),
    ...(leaf.predicate.path && { path: leaf.predicate.path }),
    ...(leaf.predicate.method && { method: leaf.predicate.method }),
    ...(leaf.predicate.expect && { expect: leaf.predicate.expect }),
    ...(leaf.predicate.description && { description: leaf.predicate.description }),
  }];

  const family = leaf.predicate.type === 'css' ? 'W' :
                 leaf.predicate.type === 'html' ? 'WH' :
                 leaf.predicate.type === 'http' ? 'WP' :
                 'WC'; // content/url

  return {
    id: leaf.id,
    family,
    generator: `wpt_${leaf.taxFamily || 'unknown'}`,
    description: leaf.description || `WPT: ${leaf.id}`,
    edits: [leaf.edit],
    predicates,
    config: {
      appDir,
      gates: { staging: false, browser: false, http: false, invariants: false, vision: false },
    },
    invariants: [{
      name: 'wpt_should_detect_mismatch',
      category: 'pipeline',
      layer: 'product',
      check: (_scenario: any, result: any) => {
        if (result instanceof Error) return { passed: true, severity: 'info' as const };
        if (result.success) {
          return { passed: false, violation: 'WPT scenario: verify passed but edit should cause mismatch', severity: 'bug' as const };
        }
        return { passed: true, severity: 'info' as const };
      },
    }],
    requiresDocker: false,
    expectedSuccess: false,
  };
}

/**
 * Convert a SerializedScenario into a VerifyScenario with appropriate invariants.
 */
function deserialize(s: SerializedScenario, appDir: string): VerifyScenario {
  const invariants = buildInvariants(s);

  // Staging/browser/http gates only run when scenario explicitly opts in with requiresDocker: true.
  // Without this, Docker-available machines (Lenovo) attempt staging on every scenario,
  // and edits that break the app cause 1,236 false staging failures.
  const gates = s.gates ?? (s.requiresDocker === true
    ? undefined  // all gates enabled
    : { staging: false, browser: false, http: false });

  return {
    id: s.id,
    family: 'G', // External scenarios go in family G (edge cases / misc)
    generator: `fault_${s.intent}`,
    description: s.description,
    edits: s.edits,
    predicates: s.predicates,
    config: {
      appDir,
      gates,
    },
    invariants,
    requiresDocker: s.requiresDocker,
    expectedSuccess: s.expectedSuccess,
  };
}

/**
 * Build invariant checks based on the scenario's intent.
 */
function buildInvariants(s: SerializedScenario): InvariantCheck[] {
  const invariants: InvariantCheck[] = [];

  // Universal: should not crash
  invariants.push({
    name: 'should_not_crash',
    category: 'robustness',
    layer: 'harness',
    check: (_scenario, result) => {
      if (result instanceof Error) {
        return { passed: false, violation: `Crashed: ${result.message}`, severity: 'bug' };
      }
      return { passed: true, severity: 'info' };
    },
  });

  // Intent-specific invariants
  switch (s.intent) {
    case 'false_positive':
      // Verify was passing when it should fail → this scenario expects verify to FAIL
      invariants.push({
        name: 'should_detect_problem',
        category: 'pipeline',
        layer: 'product',
        check: (_scenario, result) => {
          if (result instanceof Error) return { passed: true, severity: 'info' };
          const r = result as VerifyResult;
          if (r.success) {
            return {
              passed: false,
              violation: `False positive still present: verify passed but should fail`,
              severity: 'bug',
            };
          }
          return { passed: true, severity: 'info' };
        },
      });
      if (s.expectedFailedGate) {
        invariants.push({
          name: `should_fail_at_${s.expectedFailedGate}`,
          category: 'gate_sequence',
          layer: 'product',
          check: (_scenario, result) => {
            if (result instanceof Error) return { passed: true, severity: 'info' };
            const r = result as VerifyResult;
            const gate = r.gates.find(g => g.gate === s.expectedFailedGate);
            if (!gate) {
              // Gate not in results — an earlier gate short-circuited.
              // If verify still failed, the scenario is "correctly failing" just at
              // a different gate. That's gate ordering, not a bug.
              if (!r.success) {
                return { passed: true, severity: 'info' };
              }
              return {
                passed: false,
                violation: `Expected gate ${s.expectedFailedGate} not found in results and verify passed`,
                severity: 'unexpected',
              };
            }
            if (gate.passed) {
              return {
                passed: false,
                violation: `Gate ${s.expectedFailedGate} should have failed but passed`,
                severity: 'bug',
              };
            }
            return { passed: true, severity: 'info' };
          },
        });
      }
      break;

    case 'false_negative':
      // Verify was failing when it should pass → this scenario expects verify to PASS
      invariants.push({
        name: 'should_accept_valid_edit',
        category: 'pipeline',
        layer: 'product',
        check: (_scenario, result) => {
          if (result instanceof Error) return { passed: true, severity: 'info' };
          const r = result as VerifyResult;
          if (!r.success) {
            const failedGate = r.gates.find(g => !g.passed);
            return {
              passed: false,
              violation: `False negative still present: verify failed at ${failedGate?.gate ?? 'unknown'} but should pass`,
              severity: 'bug',
            };
          }
          return { passed: true, severity: 'info' };
        },
      });
      break;

    case 'bad_hint':
      // Verify's narrowing was misleading → check that narrowing is present and reasonable
      invariants.push({
        name: 'narrowing_should_be_helpful',
        category: 'pipeline',
        layer: 'product',
        check: (_scenario, result) => {
          if (result instanceof Error) return { passed: true, severity: 'info' };
          const r = result as VerifyResult;
          if (!r.success && !r.narrowing?.resolutionHint) {
            return {
              passed: false,
              violation: 'Failed without narrowing hint — agent gets no guidance',
              severity: 'unexpected',
            };
          }
          return { passed: true, severity: 'info' };
        },
      });
      break;

    case 'regression_guard':
      // General regression — just check expectedSuccess matches
      invariants.push({
        name: 'outcome_matches_expected',
        category: 'pipeline',
        layer: 'product',
        check: (_scenario, result) => {
          if (result instanceof Error) return { passed: true, severity: 'info' };
          const r = result as VerifyResult;
          if (r.success !== s.expectedSuccess) {
            return {
              passed: false,
              violation: `Expected ${s.expectedSuccess ? 'pass' : 'fail'} but got ${r.success ? 'pass' : 'fail'}`,
              severity: 'bug',
            };
          }
          return { passed: true, severity: 'info' };
        },
      });
      break;
  }

  return invariants;
}
